Ardenian
Idrinth/IDotD pull request #205
Opened 2016-10-11 19:44 UTC by Ardenian

Pull Request to add changes based on Ticket #191

2016-10-11 20:02 UTC, Idrinth commented on src/mods/chat.js
> +            var login = document.getElementById ( 'idrinth-chat-login' ).getElementsByTagName ( 'input' )[0].value;
var login = document.getElementById ( 'idrinth-chat-login' ).getElementsByTagName ( 'input' );

Doesn't have any benefit otherwise

2016-10-11 20:29 UTC, Idrinth commented
LGTM
let's see if I may still allow this

2016-10-11 21:09 UTC, Idrinth requested changes

2016-10-11 21:09 UTC, Idrinth commented on src/mods/tier.js
> +                if ( data[key].name && idrinth.settings.get ( "bannedRaids#" + data[key].name ) === undefined ) {
this line has the bug - not yours, but still :P

2016-10-11 21:31 UTC, Idrinth approved these changes

2016-10-12 04:58 UTC, w20k commented
LGTM

2016-10-12 04:58 UTC, merged