de.json language pack
Idrinth/IDotD pull request #229
Opened 2016-11-07 17:38 UTC by Ardenian

Needs #228 to be solved and closed

2016-11-10 15:24 UTC, Idrinth requested changes

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "raidsearch": "Idrinth's Raidsearch",
's is english only

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "timeAutoJoin": "Zeit, um langsam automatisch Raids beizutreten ( l�dt Spiel mehrere Male neu). Format ist [Hours]:[Minutes] ohne anf�hrende Nullen, also 7:1 ist gut, 07:01 ist schlecht",
wasn't completely translated

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "disableTimedAutoJoin": "Deaktiviere zeitlich-automatisches Beitreten",
zeitlich-automatisch? What about something like geplantes?

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "refreshFBGameLogin": "Erneuere Facebook Login",
Game is missing, it's not about logging ino facebook.

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "reloadScript": "Skript neuladen",
this and the above sound weird, "Lade X neu" maybe?

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "cancel": "Schlie�en",
Abbrechen

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +            "manually": "Importiere alle manuell",
alle was?

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "disableJoining": "Deaktiviere Beitreten der Raids ",
sounds horrible, like a omputer voice being made to sound like a robot - would propose moving the deactivation to the end.

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "lastJoined": "Letzte beigetretene Raids",
Zuletzt...

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "maxBoxes": "Es gibt keinen Platz f�r eine weitere Tierbox , bitte Schlie�en Sie eine."
Tierbox? Schließen lower case, Sie doesn't fit to the context, du would be better.

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "tag": "Tag to screen-top",
not translated

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "diff": {
children not translated

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "hour": " Gold pro Stunde jeweils",
jeweils -> und Gebäude

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +    "default": "Unexpected error occurred. Please contact script developers (https://github.com/Idrinth/IDotD).",
not translated

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +        "notification": {
not translated

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +            "creditEmoticon": "Emoticons bereitgestellt durch ",
bereitgestellt -> erschaffen, erstellt o.ä.

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +            "settings": "Mehr Einstellungen bei ",
bei -> auf

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +            "copyIdPasswort": "Kopiere Passwort&Id",
copy to the end of the sentence

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +            "invite": "Zum Chat einladen ",
Zu, not Zum

2016-11-10 15:24 UTC, Idrinth commented on src/languages/de.json
> +            "banUser": "Ban Benutzer",
all the user ranks are not fully translated or not translated at all.

2016-11-10 19:16 UTC, Ardenian commented on src/languages/de.json
> +            "banUser": "Ban Benutzer",
Well, I am not sure how to translate 'ban', I'd expect gamers to know what it means. 'Verbanne Benutzer' does not sound very beautiful, does it. 
As for the other ones, Admin and Moderator should be appropriate, the term 'Promote' should be an equivalent to 'make', in any other case I would need some help on finding the correct term.

2016-11-10 19:17 UTC, Ardenian commented on src/languages/de.json
> +            "copyIdPasswort": "Kopiere Passwort&Id",
Please rephrase, after my understanding it would be 'Passwort&Id kopiere'

2016-11-10 19:18 UTC, Ardenian commented on src/languages/de.json
> +            "creditEmoticon": "Emoticons bereitgestellt durch ",
Changed to 'erstellt'

2016-11-10 19:18 UTC, Ardenian commented on src/languages/de.json
> +    "default": "Unexpected error occurred. Please contact script developers (https://github.com/Idrinth/IDotD).",
Fixed: 
"Ein unerwareteter Fehler ist eingetreten. Bitte kontaktiere den Entwickler auf (https://github.com/Idrinth/IDotD)."

2016-11-10 19:21 UTC, Ardenian commented on src/languages/de.json
> +        "tag": "Tag to screen-top",
Changed ( shouldn't call it fixed, right): 
"An den oberen Bildschirmrand anheften"

2016-11-10 19:22 UTC, Ardenian commented on src/languages/de.json
> +        "disableTimedAutoJoin": "Deaktiviere zeitlich-automatisches Beitreten",
Changed it to that, though it is rather hard to understand for non-Coders, imo

2016-11-10 19:23 UTC, Ardenian commented on src/languages/de.json
> +            "invite": "Zum Chat einladen ",
Fixed

2016-11-10 19:23 UTC, Ardenian commented on src/languages/de.json
> +            "settings": "Mehr Einstellungen bei ",
Changed

2016-11-10 19:24 UTC, Ardenian commented on src/languages/de.json
> +        "notification": {
It is unclear to me how to translate this term. Something like "Benachrichtigungen für Chat-Nachrichten" ?

2016-11-10 19:26 UTC, Ardenian commented on src/languages/de.json
> +        "hour": " Gold pro Stunde jeweils",
Changed

2016-11-10 19:27 UTC, Ardenian commented on src/languages/de.json
> +        "diff": {
I don't think translating the difficulty names does make sense, what would you say ? In the end, it does not offer any advantage, does it.

2016-11-10 19:28 UTC, Ardenian commented on src/languages/de.json
> +        "lastJoined": "Letzte beigetretene Raids",
Changed

2016-11-10 19:29 UTC, Ardenian commented on src/languages/de.json
> +        "disableJoining": "Deaktiviere Beitreten der Raids ",
changed

2016-11-10 19:29 UTC, Ardenian commented on src/languages/de.json
> +            "manually": "Importiere alle manuell",
Fixed and clarified

2016-11-10 19:29 UTC, Ardenian commented on src/languages/de.json
> +        "cancel": "Schlie�en",
Changed

2016-11-10 19:30 UTC, Ardenian commented on src/languages/de.json
> +        "reloadScript": "Skript neuladen",
Sounds better, I agree, changed

2016-11-10 19:30 UTC, Ardenian commented on src/languages/de.json
> +        "refreshFBGameLogin": "Erneuere Facebook Login",
added

2016-11-10 19:31 UTC, Ardenian commented on src/languages/de.json
> +        "timeAutoJoin": "Zeit, um langsam automatisch Raids beizutreten ( l�dt Spiel mehrere Male neu). Format ist [Hours]:[Minutes] ohne anf�hrende Nullen, also 7:1 ist gut, 07:01 ist schlecht",
fixed

2016-11-10 19:31 UTC, Ardenian commented on src/languages/de.json
> +        "raidsearch": "Idrinth's Raidsearch",
fixed

2016-11-10 19:39 UTC, Idrinth commented on src/languages/de.json
> +    "default": "Unexpected error occurred. Please contact script developers (https://github.com/Idrinth/IDotD).",
die Entwickler (

2016-11-10 19:40 UTC, Idrinth commented on src/languages/de.json
> +            "banUser": "Ban Benutzer",
promote=befördern

2016-11-10 19:42 UTC, Ardenian commented on src/languages/de.json
> +            "banUser": "Ban Benutzer",
Isn't that exactly what happens when you 'make a user a moderator' ? I might get these make thingies on the wrong end

2016-11-10 19:43 UTC, Ardenian commented on src/languages/de.json
> +    "default": "Unexpected error occurred. Please contact script developers (https://github.com/Idrinth/IDotD).",
changed

2016-11-14 13:18 UTC, Idrinth commented on src/languages/de.json
> +            "copyIdPasswort": "Kopiere Passwort&Id",
obviously adjust it, "Passwort&Id kopieren"

2016-11-14 13:19 UTC, Idrinth commented on src/languages/de.json
> +            "banUser": "Ban Benutzer",
The point is you half-translated most of those things, "Promote zu Admin" is wierd, ban is usually germanized, so "Benutzer bannen" would make more sense.

2016-11-14 14:03 UTC, Ardenian commented on src/languages/de.json
> +            "banUser": "Ban Benutzer",
Aight, changed

2016-11-18 16:07 UTC, Idrinth approved these changes

2016-11-18 16:08 UTC, Idrinth commented
LGTM

2016-11-18 16:08 UTC, merged