Ardenian patch 1
Idrinth/IDotD pull request #237
Opened 2016-12-06 15:25 UTC by Ardenian

fixes #235

2016-12-06 15:37 UTC, Idrinth commented on src/stable.js
> +            idrinth.text.start()
where is the semicolon? :P

2016-12-06 17:24 UTC, Idrinth commented
besides a setting to set the language code it does now work.
Resetting the default might make some sense, so we don't force english on everyone by accident.

2016-12-28 08:51 UTC, Idrinth requested changes

2016-12-28 08:51 UTC, Idrinth commented on src/mods/text.js
> +    data: JSON.parse ( language+'.json' ),
this can't have been tested, it'll break the whole thing.

2016-12-28 08:51 UTC, Idrinth commented on src/mods/text.js
> +        idrinth.settings.change( "language", language );
lgtm

2016-12-28 08:54 UTC, Idrinth commented
"Resetting the default might make some sense, so we don't force english on everyone by accident." was refering to our currently set default value.
If you could move the setting, so that the language is "reset"

2017-01-04 12:34 UTC, Idrinth submitted a review, later dismissed

2017-01-04 12:34 UTC, Idrinth commented on src/mods/text.js
> +        var language = idrinth.settings.get( "lang" ) || window.navigator.userLanguage || window.navigator.language || idrinth.settings.get( "language" );
the 4th option makes no sense

2017-01-04 12:34 UTC, Idrinth commented on src/mods/settings.js
>          language: 'en',
why is this still around?

2017-01-04 17:11 UTC, Ardenian commented on src/mods/text.js
> +        var language = idrinth.settings.get( "lang" ) || window.navigator.userLanguage || window.navigator.language || idrinth.settings.get( "language" );
I did change it: https://github.com/IDotD/Userscript/pull/237/commits/0aece27e43cbf73ffdd86f46f8308d8e51eee3e8

2017-01-04 17:12 UTC, Ardenian commented on src/mods/settings.js
>          language: 'en',
Changed this one as well: https://github.com/IDotD/Userscript/pull/237/commits/8274fa6b1df818280cfa892314d862ef068b1629

Maybe something got mixed up ?

2017-01-04 18:43 UTC, Idrinth commented
my mistake, did everything work when you tested it live?

2017-01-04 23:21 UTC, Ardenian commented
Well, at first it broke my Raids tab: 
![issue](https://cloud.githubusercontent.com/assets/22526933/21662765/07567810-d2dc-11e6-9d18-94aeca3bdc3a.PNG)
However, I was not able to reproduce this issue after refreshing. 
Could you take a short look on testing, please ? I changed my browser's language setting, however, it does not actually change the language globally ( all sites, not only the script). Not sure what's causing that, nonetheless, English showed up in the user script as language.

2017-01-05 10:30 UTC, Idrinth commented
>  I changed my browser's language setting, however, it does not actually change the language globally ( all sites, not only the script). Not sure what's causing that, nonetheless, English showed up in the user script as language.

The language is submitted as a request to websites, they decide what(if anything) to do with it.
The script will already have saved the "en" when you opened it for testing before changing it I assume, maybe have a look at the three relevant values in your case? :)

2017-01-05 10:37 UTC, Idrinth commented
Generally speaking it seems to work - with a small amount of exceptions:
![de](https://cloud.githubusercontent.com/assets/7874631/21677651/56b1c8d8-d33b-11e6-8620-e29a1300559d.png)

2017-01-06 00:37 UTC, Ardenian commented
1. I missed setting.language previously, it should be fixed now with the previous commit.
2. ui.settingInfo seems to have a valid path though, it should show up. 
Only these two exceptions ?

The input field does not show up for me: 
![settings](https://cloud.githubusercontent.com/assets/22526933/21703080/d0879b8c-d3af-11e6-9647-2362b4f225b0.PNG)

Has it a script dependency other than idrinth.de, like ajax.googleapi.com or something ?
I get these two error messages in my Firefox console: 
> [IDotDS] JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> "[IDotDS] Request to https://dotd.idrinth.de/armorgames/raid-service/-1/ failed."

2017-01-06 08:44 UTC, Idrinth commented
The error sounds like my server failed to answer when you requested raids, will have a look, but it's unrelated.
You are testing your own version, right?

```
var sc = document.createElement ( 'script' );
sc.setAttribute ( 'src', 'https://dotd.idrinth.de/static/userscript/Ardenianpatch1/' );
document.getElementsByTagName ( 'body' )[0].appendChild ( sc );
```

regarding the setting.language, remember to adjust the translation files as well ;)

2017-01-06 11:40 UTC, Idrinth commented
LGTM

2017-01-06 12:26 UTC, Idrinth commented
Approved? :D I hate changing checks

2017-01-06 12:26 UTC, Idrinth commented
:+1:

2017-01-06 12:27 UTC, Idrinth commented
lgtm

2017-01-06 12:27 UTC, merged